version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
    - 27017:27017
    volumes:
      - ./data:/data/db
    container_name: mongo
    networks:
      - app_network
  express:
    build:
      context: ./api
      dockerfile: ./api/api-dockerfile
    image: alma-connector-api:latest
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    volumes:
      - ./api:/api
    networks:
      - app_network
    container_name: api
  mongoex:
    image: mongo-express
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=test
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - 8081:8081
    links:
      - mongodb
    networks:
      - app_network
  react:
    build:
      context: ./client
      dockerfile: ./client/client-dockerfile
    image: alma-connector-client:latest
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    networks:
      - app_network
    container_name: client
networks:
  app_network:
    driver: bridge
